// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// PageReader is an autogenerated mock type for the PageReader type
type PageReader struct {
	mock.Mock
}

// GetPageContents provides a mock function with given fields: url
func (_m *PageReader) GetPageContents(url string) (io.ReadCloser, error) {
	ret := _m.Called(url)

	var r0 io.ReadCloser
	if rf, ok := ret.Get(0).(func(string) io.ReadCloser); ok {
		r0 = rf(url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPageReader creates a new instance of PageReader. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewPageReader(t testing.TB) *PageReader {
	mock := &PageReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
