// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// RobotsList is an autogenerated mock type for the RobotsList type
type RobotsList struct {
	mock.Mock
}

// Contains provides a mock function with given fields: url
func (_m *RobotsList) Contains(url string) bool {
	ret := _m.Called(url)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Print provides a mock function with given fields:
func (_m *RobotsList) Print() {
	_m.Called()
}

// NewRobotsList creates a new instance of RobotsList. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewRobotsList(t testing.TB) *RobotsList {
	mock := &RobotsList{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
